### ISSUE TITLE
Move prototype changes from lotus-api-playground to libraries

### ISSUE THREAD

**Issue by mishmosh** [filecoin-shipyard/js-lotus-client#30]

**Comment by jimpick** [comment]
Updated:

0.0.6: https://www.npmjs.com/package/@filecoin-shipyard/lotus-client-schema 
0.0.3: https://www.npmjs.com/package/@filecoin-shipyard/lotus-client-rpc
0.0.3: https://www.npmjs.com/package/@filecoin-shipyard/lotus-client-provider-browser
