### ISSUE TITLE
Write up feedback from session with @jimmylee

### ISSUE THREAD

**Issue by mishmosh** [filecoin-shipyard/js-lotus-client#6]

**Comment by jimpick** [comment]
- 90 minute Zoom session on 2020.03.31 with @jimmylee
- first internal tech level review of the initial library at https://github.com/filecoin-shipyard/js-lotus-client
- walked through some of the code examples, talked about direction and strategy
- generally seemed to be in alignment on ideas and prioritization
- excited to use @jimmylee as a sounding board for ideas going forward :-)

**Comment by jimpick** [comment]
Meta: For these feedback summary notes, we're going to keep the issues open in GitHub for a week for visibility, and then close them.

**Comment by mishmosh** [comment]
@jimpick can you add more detail about what you reviewed discussed? (Imagine someone else in the future trying to learn from this issue writeup.)
